# -*- coding: utf-8 -*-
"""Alice And Bob in streamcipher Authentitication.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16FmHBGQXGU-o6P4kpJbrZk0MWmocSyfa
"""

import random
class KeyStream:
  def _init_(self,key1):
    self.next=key
  def rand(self):
    self.next = (1103515245*self.next + 12345)% 2**31
  def get_key_byte(self):
    return self.rand() % 256
  def encrypt(key,message):
    return bytes([message[i]^key.get_key_byte() for i in range(len(message))])

  def transmit(cipher, likely):
    b = []
    for c in cipher:
     if random.randrange(0,likely) ==0:
       c = c^random.randrange(0,8)
       b.append(c)
       return bytes[b]

   
    key = KeyStream(10)
    message = "Hello World".encode()
    print(message)
    cipher = encrypt(key,message)
    print(cipher)
    cipher = transmit(cipher,5)
    key = keyStream(10)
    message = encrypt(key,cipher)
    print(key)
    for i in range(10):
      print(key.get_key_byte())

      def modification(cipher):
        mod = [0]*len(cipher)
        mod[10] = ord('') ^ ord('1')
        mod[11] = ord('') ^ ord('0')
        mod[12] = ord('') ^ ord('0')

        return bytes([mod[i]^cipher[i] for i in range(len(cipher))])

      #This is Alice
      key = KeyStream(10)
      message = "send bank 10$".encode()
      print(message)
      cipher = encrypt(key,message)
      print(cipher)
      #This is bob
      key = KeyStream(10)
      message = encrypt(key,message)
      print(key)